// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3dI8GoymQ6O9NuH5s40BKbCU5ub9vFA0',
    appId: '1:461688810503:web:f0c51b27d8cf3ffce88ea2',
    messagingSenderId: '461688810503',
    projectId: 'ya-homework',
    authDomain: 'ya-homework.firebaseapp.com',
    storageBucket: 'ya-homework.appspot.com',
    measurementId: 'G-SKMPGP8ZE3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsyygV8jwJx0zhz_1wgGBY0U30bKqhNXw',
    appId: '1:461688810503:android:21b845116a8b517be88ea2',
    messagingSenderId: '461688810503',
    projectId: 'ya-homework',
    storageBucket: 'ya-homework.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6QjGl8uS4A_NH57k6ysLCEdPKaY9Aldg',
    appId: '1:461688810503:ios:64cdf21439db5453e88ea2',
    messagingSenderId: '461688810503',
    projectId: 'ya-homework',
    storageBucket: 'ya-homework.appspot.com',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6QjGl8uS4A_NH57k6ysLCEdPKaY9Aldg',
    appId: '1:461688810503:ios:64cdf21439db5453e88ea2',
    messagingSenderId: '461688810503',
    projectId: 'ya-homework',
    storageBucket: 'ya-homework.appspot.com',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3dI8GoymQ6O9NuH5s40BKbCU5ub9vFA0',
    appId: '1:461688810503:web:7f23bbecac026f34e88ea2',
    messagingSenderId: '461688810503',
    projectId: 'ya-homework',
    authDomain: 'ya-homework.firebaseapp.com',
    storageBucket: 'ya-homework.appspot.com',
    measurementId: 'G-WVN65H68SP',
  );
}
