name: Flutter PR

on:
  pull_request:
    branches:
      - main
      - dev
    paths-ignore:
      - ".vscode/**"
jobs:
  analyze:
    name: Run Flutter analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter analyze --no-fatal-infos
      - run: dart format --set-exit-if-changed .
    timeout-minutes: 10

  test:
    name: Run Flutter test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter test
    timeout-minutes: 10

  build:  
    name: Build Android
    env:
      BASE_URL: ${{secrets.BASE_URL}}
      API_KEY: ${{secrets.BASE_API_KEY}}
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build apk --release --dart-define-from-file=dev_config.json --dart-define=DEFINE_BASE_URL=BASE_URL --dart-define=DEFINE_API_KEY=API_KEY
    timeout-minutes: 10
       
  
