name: Flutter PR

on:
  pull_request:
    branches:
      - main
      - dev
    paths-ignore:
      - ".vscode/**"
jobs:
  analyze:
    name: Run Flutter analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter analyze --no-fatal-infos
      - run: dart format --set-exit-if-changed .
    timeout-minutes: 10

  test:
    name: Run Flutter test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter test
    timeout-minutes: 10


  build-dev:  
    name: Build and publish dev-APK

    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter build apk ${{secrets.DEV_BUILD_ENV}} --dart-define=DEFINE_API_KEY=${{secrets.BASE_API_KEY}} --dart-define=DEFINE_BASE_URL=${{secrets.BASE_URL}}
      - name: Publish DEV to Firebase
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          file: build/app/outputs/flutter-apk/app-release.apk
          appId: ${{secrets.FIREBASE_DEV_APP_ID}}
          serviceCredentialsFileContent: ${{secrets.CREDENTIAL_FILE_CONTENT}}
     
    timeout-minutes: 10

  build-release:  
    name: Build and publish release-APK
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter build apk ${{secrets.RELEASE_BUILD_ENV}} --dart-define=DEFINE_API_KEY=${{secrets.BASE_API_KEY}} --dart-define=DEFINE_BASE_URL=${{secrets.BASE_URL}}
      - name: Publish release to Firebase
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          file: build/app/outputs/flutter-apk/app-release.apk
          appId: ${{secrets.FIREBASE_APP_ID}}
          serviceCredentialsFileContent: ${{secrets.CREDENTIAL_FILE_CONTENT}}

    timeout-minutes: 10
       
  
